#!/usr/bin/env python3
"""
Valida nombres de territorios de fuente externa contra polígonos oficiales.

Uso:
  python backend/validate_map_localidades.py ^
    --source-file C:/ruta/listado_territorios.csv --source-column "territorio" ^
    --geojson backend/data/barrios_jamundi_valle.geojson backend/data/barrios_jamundi_valle_extra.geojson ^
    --aliases-out backend/data/barrios_official_aliases_autogenerated.json ^
    --dry-run

Salida:
  - Revisa cuántos territorios no tienen match por normalización exacta.
  - Genera sugerencias por similitud (difflib) para acelerar alias.
  - Puede exportar un archivo de aliases sugerido para `barrios_official_aliases.json`.
"""

from __future__ import annotations

import argparse
import csv
import json
import unicodedata
from difflib import get_close_matches
from pathlib import Path
from typing import Iterable, List, Set, Tuple


def normalize_name(value: str) -> str:
    if not value:
        return ""
    normalized = "".join(
        char for char in unicodedata.normalize("NFD", str(value))
        if not unicodedata.combining(char)
    )
    return " ".join(normalized.upper().strip().split())


def load_geojson_names(paths: Iterable[str]) -> Tuple[Set[str], int]:
    names = set()
    total_features = 0
    for path in paths:
        p = Path(path)
        if not p.exists():
            print(f"[WARN] GeoJSON no existe: {p}")
            continue

        with p.open(encoding="utf-8") as f:
            raw = json.load(f)

        features = raw.get("features", [])
        total_features += len(features)
        for feature in features:
            props = feature.get("properties") or {}
            if not isinstance(props, dict):
                continue
            name = props.get("Nombre") or props.get("name") or props.get("NOMBRE")
            if not name:
                continue
            names.add(normalize_name(name))
    return names, total_features


def load_source_names(source_file: str, source_column: str | None = None) -> List[str]:
    path = Path(source_file)
    if not path.exists():
        raise FileNotFoundError(f"Archivo de fuente no existe: {path}")

    if path.suffix.lower() != ".csv":
        raise ValueError(f"Formato no soportado para fuente: {path.suffix}. Usa CSV.")

    with path.open(encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        return []

    if source_column is None:
        source_column = list(rows[0].keys())[0]

    return [row.get(source_column, "").strip() for row in rows if row.get(source_column)]


def main() -> int:
    parser = argparse.ArgumentParser(description="Validar mapeo de territorios con polígonos oficiales")
    parser.add_argument("--source-file", required=True, help="Archivo de fuente (CSV con territorios)")
    parser.add_argument("--source-column", default=None, help="Columna del CSV que trae el nombre del territorio")
    parser.add_argument(
        "--geojson",
        nargs="+",
        required=True,
        help="Uno o varios archivos GeoJSON (base y extra) para consultar nombres oficiales",
    )
    parser.add_argument("--aliases-out", default="backend/data/barrios_official_aliases_autogenerated.json")
    parser.add_argument("--dry-run", action="store_true", help="No escribe aliases, solo muestra reporte")
    args = parser.parse_args()

    source_names_raw = load_source_names(args.source_file, args.source_column)
    if not source_names_raw:
        print("[ERROR] No se encontraron nombres en la fuente.")
        return 1

    source_names = {normalize_name(n) for n in source_names_raw if n}
    official_names, total_features = load_geojson_names(args.geojson)

    if not official_names:
        print("[ERROR] No se cargaron nombres oficiales desde los GeoJSON.")
        return 1

    matched = sorted(source_names & official_names)
    unmatched = sorted(source_names - official_names)

    print(f"\nTotal fuente (normalizada): {len(source_names)}")
    print(f"Total polígonos cargados: {total_features}")
    print(f"Coincidentes exactos: {len(matched)}")
    print(f"No mapeados: {len(unmatched)}\n")

    suggestions = {}
    official_list = sorted(official_names)
    for name in unmatched:
        close = get_close_matches(name, official_list, n=3, cutoff=0.72)
        if close:
            print(f" - {name} -> {', '.join(close)}")
            suggestions[name] = close[0]
        else:
            print(f" - {name} -> sin sugerencia")

    if args.dry_run:
        print("\n[MODO DRY-RUN] No se escribió archivo de aliases.")
        return 0

    alias_file = Path(args.aliases_out)
    alias_file.parent.mkdir(parents=True, exist_ok=True)
    alias_file.write_text(
        json.dumps(suggestions, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    print(f"\nArchivo sugerido creado en: {alias_file}")
    print("Puedes copiar los pares requeridos a backend/data/barrios_official_aliases.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
